force-app/main/default/objects/RollbarSettings__c/RollbarSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RollbarSettings</label>
</CustomObject>

force-app/main/default/objects/RollbarSettings__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RollbarConfigureController.cls
public with sharing class RollbarConfigureController {

    public Map<String, Boolean> checks  { get; private set; }

    protected RollbarSettings__c settings { get; set; }
    public String accessToken {
        get {
            return this.settings.AccessToken__c;
        }
        set {
            this.accessToken = this.settings.AccessToken__c = value;
        }
    }

    public RollbarConfigureController() {
        this.settings = RollbarSettings__c.getOrgDefaults();
    }

    public Pagereference save()
    {
        Config config = new Config(this.accessToken, UserInfo.getOrganizationId());

        RollbarInstaller.install(config);

        return null;
    }

    public Pagereference check()
    {
        Config config = new Config(this.accessToken, UserInfo.getOrganizationId());

        this.checks = RollbarInstaller.check(config);
        
        return null;
    }
}